version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
       GO111MODULE: on
    steps:
      - checkout
      - run: build/updateapi.sh
      - run: go get -v -t -d ./...
      - run: go test -v ./...
