{
 "kind": "discovery#restDescription",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/bsAY-IFJVuG9FbzVCo5ZTE6TReM\"",
 "discoveryVersion": "v1",
 "id": "youtubePartner:v1",
 "name": "youtubePartner",
 "canonicalName": "YouTube Partner",
 "version": "v1",
 "revision": "20170911",
 "title": "Youtube Content ID API",
 "description": "API for YouTube partners. To use this API YouTube CMS account is required.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/youtube/partner/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/youtube/partner/v1/",
 "basePath": "/youtube/partner/v1/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/partner/v1/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    },
    "https://www.googleapis.com/auth/youtubepartner-content-owner-readonly": {
     "description": "View content owner account details from YouTube."
    }
   }
  }
 },
 "resources": {
  "assetLabels": {
   "methods": {
    "insert": {
     "id": "youtubePartner.assetLabels.insert",
     "path": "assetLabels",
     "httpMethod": "POST",
     "description": "Insert an asset label for an owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.assetLabels.list",
     "path": "assetLabels",
     "httpMethod": "GET",
     "description": "Retrieves a list of all asset labels for an owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "assetMatchPolicy": {
   "methods": {
    "get": {
     "id": "youtubePartner.assetMatchPolicy.get",
     "path": "assets/{assetId}/matchPolicy",
     "httpMethod": "GET",
     "description": "Retrieves the match policy assigned to the specified asset by the content owner associated with the authenticated user. This information is only accessible to an owner of the asset.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.assetMatchPolicy.patch",
     "path": "assets/{assetId}/matchPolicy",
     "httpMethod": "PATCH",
     "description": "Updates the asset's match policy. If an asset has multiple owners, each owner may set its own match policy for the asset. YouTube then computes the match policy that is actually applied for the asset based on the territories where each owner owns the asset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.assetMatchPolicy.update",
     "path": "assets/{assetId}/matchPolicy",
     "httpMethod": "PUT",
     "description": "Updates the asset's match policy. If an asset has multiple owners, each owner may set its own match policy for the asset. YouTube then computes the match policy that is actually applied for the asset based on the territories where each owner owns the asset.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "assetRelationships": {
   "methods": {
    "delete": {
     "id": "youtubePartner.assetRelationships.delete",
     "path": "assetRelationships/{assetRelationshipId}",
     "httpMethod": "DELETE",
     "description": "Deletes a relationship between two assets.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.assetRelationships.insert",
     "path": "assetRelationships",
     "httpMethod": "POST",
     "description": "Creates a relationship that links two assets.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.assetRelationships.list",
     "path": "assetRelationships",
     "httpMethod": "GET",
     "description": "Retrieves a list of relationships for a given asset. The list contains relationships where the specified asset is either the parent (embedding) or child (embedded) asset in the relationship.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "assetSearch": {
   "methods": {
    "list": {
     "id": "youtubePartner.assetSearch.list",
     "path": "assetSearch",
     "httpMethod": "GET",
     "description": "Searches for assets based on asset metadata. The method can retrieve all assets or only assets owned by the content owner. This method mimics the functionality of the advanced search feature on the Assets page in CMS.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "assetShares": {
   "methods": {
    "list": {
     "id": "youtubePartner.assetShares.list",
     "path": "assetShares",
     "httpMethod": "GET",
     "description": "This method either retrieves a list of asset shares the partner owns and that map to a specified asset view ID or it retrieves a list of asset views associated with a specified asset share ID owned by the partner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "assets": {
   "methods": {
    "get": {
     "id": "youtubePartner.assets.get",
     "path": "assets/{assetId}",
     "httpMethod": "GET",
     "description": "Retrieves the metadata for the specified asset. Note that if the request identifies an asset that has been merged with another asset, meaning that YouTube identified the requested asset as a duplicate, then the request retrieves the merged, or synthesized, asset.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.assets.insert",
     "path": "assets",
     "httpMethod": "POST",
     "description": "Inserts an asset with the specified metadata. After inserting an asset, you can set its ownership data and match policy.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.assets.list",
     "path": "assets",
     "httpMethod": "GET",
     "description": "Retrieves a list of assets based on asset metadata. The method can retrieve all assets or only assets owned by the content owner.\n\nNote that in cases where duplicate assets have been merged, the API response only contains the synthesized asset. (It does not contain the constituent assets that were merged into the synthesized asset.)",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.assets.patch",
     "path": "assets/{assetId}",
     "httpMethod": "PATCH",
     "description": "Updates the metadata for the specified asset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.assets.update",
     "path": "assets/{assetId}",
     "httpMethod": "PUT",
     "description": "Updates the metadata for the specified asset.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "campaigns": {
   "methods": {
    "delete": {
     "id": "youtubePartner.campaigns.delete",
     "path": "campaigns/{campaignId}",
     "httpMethod": "DELETE",
     "description": "Deletes a specified campaign for an owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "get": {
     "id": "youtubePartner.campaigns.get",
     "path": "campaigns/{campaignId}",
     "httpMethod": "GET",
     "description": "Retrieves a particular campaign for an owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.campaigns.insert",
     "path": "campaigns",
     "httpMethod": "POST",
     "description": "Insert a new campaign for an owner using the specified campaign data.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.campaigns.list",
     "path": "campaigns",
     "httpMethod": "GET",
     "description": "Retrieves a list of campaigns for an owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.campaigns.patch",
     "path": "campaigns/{campaignId}",
     "httpMethod": "PATCH",
     "description": "Update the data for a specific campaign. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.campaigns.update",
     "path": "campaigns/{campaignId}",
     "httpMethod": "PUT",
     "description": "Update the data for a specific campaign.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "claimHistory": {
   "methods": {
    "get": {
     "id": "youtubePartner.claimHistory.get",
     "path": "claimHistory/{claimId}",
     "httpMethod": "GET",
     "description": "Retrieves the claim history for a specified claim.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "claimSearch": {
   "methods": {
    "list": {
     "id": "youtubePartner.claimSearch.list",
     "path": "claimSearch",
     "httpMethod": "GET",
     "description": "Retrieves a list of claims that match the search criteria. You can search for claims that are associated with a specific asset or video or that match a specified query string.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "claims": {
   "methods": {
    "get": {
     "id": "youtubePartner.claims.get",
     "path": "claims/{claimId}",
     "httpMethod": "GET",
     "description": "Retrieves a specific claim by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.claims.insert",
     "path": "claims",
     "httpMethod": "POST",
     "description": "Creates a claim. The video being claimed must have been uploaded to a channel associated with the same content owner as the API user sending the request. You can set the claim's policy in any of the following ways:\n- Use the claim resource's policy property to identify a saved policy by its unique ID.\n- Use the claim resource's policy property to specify a custom set of rules.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.claims.list",
     "path": "claims",
     "httpMethod": "GET",
     "description": "Retrieves a list of claims administered by the content owner associated with the currently authenticated user. Results are sorted in descending order of creation time.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.claims.patch",
     "path": "claims/{claimId}",
     "httpMethod": "PATCH",
     "description": "Updates an existing claim by either changing its policy or its status. You can update a claim's status from active to inactive to effectively release the claim. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.claims.update",
     "path": "claims/{claimId}",
     "httpMethod": "PUT",
     "description": "Updates an existing claim by either changing its policy or its status. You can update a claim's status from active to inactive to effectively release the claim.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "contentOwnerAdvertisingOptions": {
   "methods": {
    "get": {
     "id": "youtubePartner.contentOwnerAdvertisingOptions.get",
     "path": "contentOwnerAdvertisingOptions",
     "httpMethod": "GET",
     "description": "Retrieves advertising options for the content owner associated with the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.contentOwnerAdvertisingOptions.patch",
     "path": "contentOwnerAdvertisingOptions",
     "httpMethod": "PATCH",
     "description": "Updates advertising options for the content owner associated with the authenticated API user. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.contentOwnerAdvertisingOptions.update",
     "path": "contentOwnerAdvertisingOptions",
     "httpMethod": "PUT",
     "description": "Updates advertising options for the content owner associated with the authenticated API user.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "contentOwners": {
   "methods": {
    "get": {
     "id": "youtubePartner.contentOwners.get",
     "path": "contentOwners/{contentOwnerId}",
     "httpMethod": "GET",
     "description": "Retrieves information about the specified content owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.contentOwners.list",
     "path": "contentOwners",
     "httpMethod": "GET",
     "description": "Retrieves a list of content owners that match the request criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/youtubepartner-content-owner-readonly"
     ]
    }
   }
  },
  "liveCuepoints": {
   "methods": {
    "insert": {
     "id": "youtubePartner.liveCuepoints.insert",
     "path": "liveCuepoints",
     "httpMethod": "POST",
     "description": "Inserts a cuepoint into a live broadcast.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "metadataHistory": {
   "methods": {
    "list": {
     "id": "youtubePartner.metadataHistory.list",
     "path": "metadataHistory",
     "httpMethod": "GET",
     "description": "Retrieves a list of all metadata provided for an asset, regardless of which content owner provided the data.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "orders": {
   "methods": {
    "delete": {
     "id": "youtubePartner.orders.delete",
     "path": "orders/{orderId}",
     "httpMethod": "DELETE",
     "description": "Delete an order, which moves orders to inactive state and removes any associated video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "get": {
     "id": "youtubePartner.orders.get",
     "path": "orders/{orderId}",
     "httpMethod": "GET",
     "description": "Retrieve the details of an existing order.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.orders.insert",
     "path": "orders",
     "httpMethod": "POST",
     "description": "Creates a new basic order entry in the YouTube premium asset order management system. You must supply at least a country and channel in the new order.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.orders.list",
     "path": "orders",
     "httpMethod": "GET",
     "description": "Return a list of orders, filtered by the parameters below, may return more than a single page of results.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.orders.patch",
     "path": "orders/{orderId}",
     "httpMethod": "PATCH",
     "description": "Update the values in an existing order. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.orders.update",
     "path": "orders/{orderId}",
     "httpMethod": "PUT",
     "description": "Update the values in an existing order.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "ownership": {
   "methods": {
    "get": {
     "id": "youtubePartner.ownership.get",
     "path": "assets/{assetId}/ownership",
     "httpMethod": "GET",
     "description": "Retrieves the ownership data provided for the specified asset by the content owner associated with the authenticated user.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.ownership.patch",
     "path": "assets/{assetId}/ownership",
     "httpMethod": "PATCH",
     "description": "Provides new ownership information for the specified asset. Note that YouTube may receive ownership information from multiple sources. For example, if an asset has multiple owners, each owner might send ownership data for the asset. YouTube algorithmically combines the ownership data received from all of those sources to generate the asset's canonical ownership data, which should provide the most comprehensive and accurate representation of the asset's ownership. This method[...]",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.ownership.update",
     "path": "assets/{assetId}/ownership",
     "httpMethod": "PUT",
     "description": "Provides new ownership information for the specified asset. Note that YouTube may receive ownership information from multiple sources. For example, if an asset has multiple owners, each owner might send ownership data for the asset. YouTube algorithmically combines the ownership data received from all of those sources to generate the asset's canonical ownership data, which should provide the most comprehensive and accurate representation of the asset's ownership.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "ownershipHistory": {
   "methods": {
    "list": {
     "id": "youtubePartner.ownershipHistory.list",
     "path": "ownershipHistory",
     "httpMethod": "GET",
     "description": "Retrieves a list of the ownership data for an asset, regardless of which content owner provided the data. The list only includes the most recent ownership data for each content owner. However, if the content owner has submitted ownership data through multiple data sources (API, content feeds, etc.), the list will contain the most recent data for each content owner and data source.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "package": {
   "methods": {
    "get": {
     "id": "youtubePartner.package.get",
     "path": "package/{packageId}",
     "httpMethod": "GET",
     "description": "Retrieves information for the specified package.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.package.insert",
     "path": "package",
     "httpMethod": "POST",
     "description": "Inserts a metadata-only package.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "policies": {
   "methods": {
    "get": {
     "id": "youtubePartner.policies.get",
     "path": "policies/{policyId}",
     "httpMethod": "GET",
     "description": "Retrieves the specified saved policy.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.policies.insert",
     "path": "policies",
     "httpMethod": "POST",
     "description": "Creates a saved policy.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.policies.list",
     "path": "policies",
     "httpMethod": "GET",
     "description": "Retrieves a list of the content owner's saved policies.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.policies.patch",
     "path": "policies/{policyId}",
     "httpMethod": "PATCH",
     "description": "Updates the specified saved policy. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.policies.update",
     "path": "policies/{policyId}",
     "httpMethod": "PUT",
     "description": "Updates the specified saved policy.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "publishers": {
   "methods": {
    "get": {
     "id": "youtubePartner.publishers.get",
     "path": "publishers/{publisherId}",
     "httpMethod": "GET",
     "description": "Retrieves information about the specified publisher.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.publishers.list",
     "path": "publishers",
     "httpMethod": "GET",
     "description": "Retrieves a list of publishers that match the request criteria. This method is analogous to a publisher search function.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "referenceConflicts": {
   "methods": {
    "get": {
     "id": "youtubePartner.referenceConflicts.get",
     "path": "referenceConflicts/{referenceConflictId}",
     "httpMethod": "GET",
     "description": "Retrieves information about the specified reference conflict.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.referenceConflicts.list",
     "path": "referenceConflicts",
     "httpMethod": "GET",
     "description": "Retrieves a list of unresolved reference conflicts.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "references": {
   "methods": {
    "get": {
     "id": "youtubePartner.references.get",
     "path": "references/{referenceId}",
     "httpMethod": "GET",
     "description": "Retrieves information about the specified reference.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.references.insert",
     "path": "references",
     "httpMethod": "POST",
     "description": "Creates a reference in one of the following ways:\n- If your request is uploading a reference file, YouTube creates the reference from the provided content. You can provide either a video/audio file or a pre-generated fingerprint. If you are providing a pre-generated fingerprint, set the reference resource's fpDirect property to true in the request body. In this flow, you can use either the multipart or resumable upload flows to provide the reference content.\n- If you want [...]",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "youtubePartner.references.list",
     "path": "references",
     "httpMethod": "GET",
     "description": "Retrieves a list of references by ID or the list of references for the specified asset.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.references.patch",
     "path": "references/{referenceId}",
     "httpMethod": "PATCH",
     "description": "Updates a reference. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.references.update",
     "path": "references/{referenceId}",
     "httpMethod": "PUT",
     "description": "Updates a reference.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "validator": {
   "methods": {
    "validate": {
     "id": "youtubePartner.validator.validate",
     "path": "validator",
     "httpMethod": "POST",
     "description": "Validate a metadata file.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "validateAsync": {
     "id": "youtubePartner.validator.validateAsync",
     "path": "validatorAsync",
     "httpMethod": "POST",
     "description": "Validate a metadata file asynchronously.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "validateAsyncStatus": {
     "id": "youtubePartner.validator.validateAsyncStatus",
     "path": "validatorAsyncStatus",
     "httpMethod": "POST",
     "description": "Get the asynchronous validation status.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "videoAdvertisingOptions": {
   "methods": {
    "get": {
     "id": "youtubePartner.videoAdvertisingOptions.get",
     "path": "videoAdvertisingOptions/{videoId}",
     "httpMethod": "GET",
     "description": "Retrieves advertising settings for the specified video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "getEnabledAds": {
     "id": "youtubePartner.videoAdvertisingOptions.getEnabledAds",
     "path": "videoAdvertisingOptions/{videoId}/getEnabledAds",
     "httpMethod": "GET",
     "description": "Retrieves details about the types of allowed ads for a specified partner- or user-uploaded video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "patch": {
     "id": "youtubePartner.videoAdvertisingOptions.patch",
     "path": "videoAdvertisingOptions/{videoId}",
     "httpMethod": "PATCH",
     "description": "Updates the advertising settings for the specified video. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtubePartner.videoAdvertisingOptions.update",
     "path": "videoAdvertisingOptions/{videoId}",
     "httpMethod": "PUT",
     "description": "Updates the advertising settings for the specified video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "whitelists": {
   "methods": {
    "delete": {
     "id": "youtubePartner.whitelists.delete",
     "path": "whitelists/{id}",
     "httpMethod": "DELETE",
     "description": "Removes a whitelisted channel for a content owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "get": {
     "id": "youtubePartner.whitelists.get",
     "path": "whitelists/{id}",
     "httpMethod": "GET",
     "description": "Retrieves a specific whitelisted channel by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtubePartner.whitelists.insert",
     "path": "whitelists",
     "httpMethod": "POST",
     "description": "Whitelist a YouTube channel for your content owner. Whitelisted channels are channels that are not owned or managed by you, but you would like to whitelist so that no claims from your assets are placed on videos uploaded to these channels.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtubePartner.whitelists.list",
     "path": "whitelists",
     "httpMethod": "GET",
     "description": "Retrieves a list of whitelisted channels for a content owner.",
     "scopes": [
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  }
 }
}
